version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
      POSTGRES_DB: cloudservices
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
